model:
  vocab_size: 32768
  max_position_embeddings: 514
  num_attention_heads: 12
  num_hidden_layers: 12
  hidden_size: 768
  type_vocab_size: 1

tokenizer:
  tokenizer_path: "tokenizer/bpe_tokenizer.json"
  tokenizer_vocab_size: 32768
  pad_token: "<pad>"
  unk_token: "<unk>"
  mask_token: "<mask>"
  cls_token: "<s>"
  bos_token: "<s>"
  sep_token: "</s>"
  eos_token: "</s>"

train:
  output_dir: "./experiments/roberta_run_2"
  eval_strategy: "steps"
  save_strategy: "steps"
  num_train_epochs: 10
  eval_steps: 250
  save_steps: 250
  save_total_limit: 3
  per_device_train_batch_size: 128
  bf16: true
  dataloader_num_workers: 8
  logging_steps: 50
  # Checkpoint policy
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false

data:
  path: "./data/roberta/tokenized"

meta:
  report_to: "wandb"
  run_name: "run-2-base-124M_1_epochs10"
  project_name: "[midas]_latin_roberta"
  tags: "roberta"
  group: "base_models"
